config/routes.rb
BellaDonna::Application.routes.draw do

  devise_for :users
  root :to => "static_pages#index"
  get '/contact' => 'static_pages#contact', :as => :contact
  get '/admin' => 'static_pages#admin'

  resources :products do 
    resources :catgories 
  end

  resources :policies
  resources :services
  resources :service_types

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  resources :appointments

  resources :promotions
  get '/promotions/:id/activate_promotion' => 'promotions#activate_promotion', :as => :activate_promotion
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :is_admin?, except: [:index]
  
  def index
    @promotion = Promotion.where('is_active = ?', true)[0]
  end

  def admin
    @promotions = Promotion.all
    @policies = Policy.all
    @service_types = ServiceType.all
    @services = Service.all
    @products = Product.all
  end
end 

app/views/static_pages/admin.html.erb
<div class="admin-container container">

  <div class="col-md-12 admin-policies">
    <h2>Policies <span><%= link_to "add another", new_policy_path %></span></h2>  
    <ul>
      <% @policies.each do |p| %>
      <li>
        <h3><%= p.name %></h3>
        <p><%= p.description %></p>
        <div class="admin-links pull-right">
          <%= link_to "Edit", edit_policy_path(p), class: "edit_link" %>
          <%= link_to "Delete", p, method: :delete, class: "delete_link", remote: true %>

        </div>
      </li>
      <% end %>
    </ul>
  </div>


  <div id="promotion" class="col-md-12 admin-service-types">
    <h2>Service Types <span><%= link_to "add another", new_service_type_path %></span></h2>  
    <ul>
      <% @service_types.each do |st| %>
      <li>

        <h3><%= st.name %></h3>
        <p><%= st.description %></p>
        <p><%= st.image_url %></p>
        <div class="admin-links pull-right">
          <%= link_to "Edit", edit_service_type_path(st), class: "edit_link" %>
          <%= link_to "Delete", st, method: :delete, class: "delete_link", remote: true %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-12 admin-services">
    <h2>Services <span><%= link_to "add another", new_service_path %></span></h2>  
    <ul>
      <% @services.each do |s| %>
      <li>
        <h3><%= s.title %></h3>
        <p><%= s.description %></p>
        <p><%= s.price %></p>
        <div class="admin-links pull-right">
          <%= link_to "Edit", edit_service_path(s), class: "edit_link" %>
          <%= link_to "Delete", s, method: :delete, class: "delete_link", remote: true %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-12 admin-products">
    <h2>Products <span><%= link_to "add another", new_product_path %></span></h2>  
    <ul>
      <% @products.each do |p| %>
      <li>
        <h3><%= p.name %></h3>
        <p><%= p.description %></p>
        <p><%= p.price %></p>
        <p><%= p.image_url %></p>
        <div class="admin-links pull-right">
          <%= link_to "Edit", edit_product_path(p), class: "edit_link" %>
          <%= link_to "Delete", p, method: :delete, class: "delete_link", remote: true %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-12 promotions">
    <h2>Promotions <span><%= link_to "add another", new_promotion_path %></span></h2>  

    <ul>
      <% @promotions.each do |p| %>
      <div class="col-md-4 promotion">
        <li>
          <h2><%= p.header %></h2>
          <p><%= p.subheader %></p>
          <p><%= p.description %></p>
          <p>Date Created: <%= p.created_at.strftime("%d %b. %Y") %></p>
          <p>Promotion is: <strong><%= p.is_active == true ? "ACTIVE" : "INACTIVE" %></strong></p>
          <%= link_to "Make Active", activate_promotion_path(p.id), class: "btn btn-success" %>

          <%= link_to "Delete", p, method: :delete, class: "delete_link btn btn-danger", remote: true %>

        </li>
      </div>
      <% end %>
    </ul>
    </div>


  </div>

app/views/static_pages/index.html.erb
<div class="home">	
	
	<div id="promotions" class="center-block clearfix col-xs-12 col-sm-8 col-md-7">
		<% if @promotion != nil %>
		<figure>
			<figcaption class="center-block col-sm-10">

				<h2><%= @promotion.header %></h2>
				<hr>
				<h3><%= @promotion.subheader %></h3>
				<br>
				<p><%= @promotion.description %></p>
				<a class="btn btn-danger" href="/inquiries/new">Contact Us Today!</a>
			</figcaption>
		</figure>
		<% end %>
	</div>
</div>

<div id="mainCategories" class="center-block clearfix row">
	<figure class="container">
		<img class="pull-left img-circle img-responsive" src="/assets/man-massage.jpg" />
		<figcaption class="col-xs-8 col-md-9">
			<h2>Skin Treatments</h2>
			<p class="hidden-xs">Say goodbye to cookie-cutter facials! Our Dermalogica skin treatments are 100% customized to your skin's needs with a thorough skin analysis, making it a personalized treatment created especially for your skin's needs!</p>

			<a id="skinTreatments" class="btn btn-danger" href="/services">Get Details</a>
		</figcaption>
	</figure>
<hr />
		<figure class="container">
		<img class="img-circle img-responsive" src="/assets/circle_honey.jpg" />
		<figcaption class="text-right col-xs-8 col-md-9">
			<h2>BODY SUGARING</h2>
			<p class="hidden-xs">
The art of body sugaring is a form of hair removal that originated in ancient Egypt when a smooth, hairless body was the standard of youth and beauty. Sugar paste is an all natural product made from sugar, lemon and water. Great for any part of the body! 
			</p>
			<a id="bodySugaring" class="btn btn-danger" href="/services">Get Details</a>
		</figcaption>
	</figure>
<hr />
		<figure class="container">
		<img class="pull-left img-circle img-responsive" src="/assets/circle_relax.jpg" />
		<figcaption class="col-xs-8 col-md-9">
			<h2>Spa Policies</h2>
			<p class="hidden-xs">
As a courtesy to other guests and our spa therapists, if you must cancel or reschedule an appointment we require that you give at least 24 hours notice.  Cancellations made with less than 24 hours of your appointment will be charged a $10 fee.  “No-shows” will be charged 50% of the treatment price.  Appointments made the "day of" are considered confirmed to which the cancellation policy does apply.
			</p>
			<a class="btn btn-danger" href="/policies">Get Details</a>
		</figcaption>
	</figure>
</div>
