config/routes.rb
BellaDonna::Application.routes.draw do

  devise_for :users
  root :to => "static_pages#index"
  get '/contact' => 'static_pages#contact', :as => :contact
  get '/admin' => 'static_pages#admin'

  resources :products do 
    resources :catgories 
  end

  resources :policies
  resources :services
  resources :service_types

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  resources :appointments

  resources :promotions
  get '/promotions/:id/activate_promotion' => 'promotions#activate_promotion', :as => :activate_promotion
end

app/views/shared/_appointment_banner.html.erb
<div class="appointment_banner">
<a href="/appointments/new">Schedule an Appointment Now!</a>
</div>

app/views/shared/_form_errors.html.erb
<div class="form-errors">
  <% if object.errors.any?  %>
    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_top_navbar.html.erb
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand main" href="/">BellaDonna</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li class="main"><%= link_to "Products", products_path, class: cp(products_path) %></li>
            <li class="main"><%= link_to "Policies", policies_path, class: cp(policies_path) %></li>
            <li class="main"><%= link_to "Services", services_path, class: cp(services_path) %></li>
            <li class="main"><%= link_to "Contact", new_inquiry_path, class: cp(new_inquiry_path) %></li>
            
            <%if user_signed_in? && is_admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Admin Home", admin_path, class: cp(admin_path) %></li>
                <li><%= link_to "Add Policy", new_policy_path, class: cp(new_policy_path) %></li>
                <li><%= link_to "Add Product", new_product_path, class: cp(new_product_path) %></li>
                <li><%= link_to "Add Promotion", new_promotion_path, class: cp(new_promotion_path) %></li>
                <li><%= link_to "Add Service", new_service_path, class: cp(new_service_path) %></li>
                <li><%= link_to "Add Service Type", new_service_type_path, class: cp(new_service_type_path) %></li>
                <li class="main"><%= link_to "My Appointments", appointments_path, class: cp(appointments_path) %></li>
                <li class="main"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>